platform:ios, '10.0'
  
inhibit_all_warnings!

target 'MVVM Demo' do

#    def shared_pods

    pod 'Masonry',              '~> 1.0.2'
    pod 'MJRefresh'
    pod 'MJExtension'
    pod 'SDWebImage',           '~>3.7'
    pod 'AFNetworking',         '~> 3.1.0'
    pod 'ReactiveObjC'
    pod 'YYCache',              '~> 1.0.3'
    pod 'SVProgressHUD'
    pod 'MJRefresh'
    
end

